# Generated by Django 6.0.4 on 2026-05-23 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_patientprofile_credits_and_more'),
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availableslot',
            name='is_booked',
        ),
        migrations.AddField(
            model_name='availableslot',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('confirmed', 'Confirmed'), ('deleted', 'Deleted')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='appointments.availableslot'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending_request', 'Pending request'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending_request', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending_request', 'confirmed'])), fields=('slot', 'patient'), name='unique_active_appointment_per_slot_per_patient'),
        ),
    ]
