# Generated by Django 6.0.4 on 2026-05-13 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psychologistprofile',
            name='specialty',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='psychologistprofile',
            name='country_code',
            field=models.CharField(default='ES', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='psychologistprofile',
            name='license_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('psychologist', 'Psychologist'), ('developer', 'Developer')], max_length=20),
        ),
    ]
