# Generated by Django 6.0.4 on 2026-05-18 11:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_psychologistprofile_specialty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologistprofile',
            name='session_duration_minutes',
            field=models.PositiveIntegerField(default=55),
        ),
        migrations.AlterField(
            model_name='psychologistprofile',
            name='country_code',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='psychologistprofile',
            name='license_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='This field can only contain letters and hyphens.', regex='^[a-zA-ZñÑáéíóúÁÉÍÓÚ-]+$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='This field can only contain letters and hyphens.', regex='^[a-zA-ZñÑáéíóúÁÉÍÓÚ-]+$')]),
        ),
    ]
