# Generated by Django 6.0.4 on 2026-05-20 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_psychologistprofile_session_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='UTC', help_text='IANA timezone string, e.g. "Europe/Madrid"', max_length=64),
        ),
    ]
