# Generated by Django 6.0.4 on 2026-05-23 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='credits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='psychologistprofile',
            name='session_price',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=4),
        ),
    ]
