# Generated by Django 6.0.4 on 2026-05-29 15:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_patientprofile_credits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='This field can only contain letters and hyphens.', regex='^[a-zA-ZñÑáéíóúÁÉÍÓÚ- ]+$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='This field can only contain letters and hyphens.', regex='^[a-zA-ZñÑáéíóúÁÉÍÓÚ- ]+$')]),
        ),
    ]
