services:
  app:
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    container_name: django_app
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - ../.env
    environment:
      DB_ENGINE: ${DB_ENGINE:-django.db.backends.mysql}
      DB_NAME: ${DB_NAME:-psico_db}
      DB_USER: ${DB_USER:-root}
      DB_PASSWORD: ${DB_PASSWORD:-}
      DB_HOST: ${DB_HOST:-host.docker.internal}
      DB_PORT: ${DB_PORT:-3306}
    
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - "8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"


  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media

volumes:
  static_volume:
  media_volume: