services:
  django:
    build:
      context: ./django
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/staticfiles

  react:
    build:
      context: ./react/getbetter

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./react/getbetter/dist:/var/www/react
      - static_volume:/var/www/static:ro
    depends_on:
      - django
      - react

volumes:
  static_volume: