services:
  django:
    build:
      context: ./django
    volumes:
      - static_volume:/app/staticfiles
    env_file:
      - ./.local.env
    ports:
      - "8000:8000"

  react:
    build:
      context: ./react/getbetter

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./react/getbetter/dist:/var/www/react
      - static_volume:/var/www/static:ro
    depends_on:
      - django
      - react
    ports:
      - "80:80"

volumes:
  static_volume: