resolver 127.0.0.11 valid=10s; # Para que use el DNS de Docker en tiempo real

upstream django_cluster {
    zone django_cluster 64k; # Zona de memoria necesaria para que nginx pueda resolver los nombres de los contenedores
    server django_app:8000 resolve; # 'resolve' para que nginx pueda resolver el nombre del contenedor
    server django_app_2:8000 resolve; # 'resolve' para que nginx pueda resolver el nombre del contenedor
}

server {
    listen 80;

    location / {
        proxy_pass http://django_cluster;

        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_next_upstream error timeout http_502 http_503 http_504;
    }

    location /static/ {
        alias /app/staticfiles/;
        access_log off;
        expires 30d;
    }

    location /media/ {
        alias /app/media/;
        access_log off;
        expires 30d;
    }
}